# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Madeleines
tagline:          ''
description:      'Tiny pieces of delightful ideas'
url:              https://xgfd.github.io
baseurl:          /
rss_path:         feed.xml

author:
  name:           'Xgfd'
  url:            https://xgfd.github.io
  email: xinxinbird@gmail.com 
  github: xgfd
  #twitter: dbtek
  #pinterest: asd123
  linkedin: xinwang42
  #bio: Your stylish, minimalist theme!
  email_md5: ab084080a2c79b0c7055fef19556dade

gems: [jekyll-paginate,jekyll-gist]

paginate: 5
paginate_path: "page:num"

# Custom vars
#version:          2.1.0
#
github:
  repo:           https://github.com/xgfd/xgfd.github.io
